#!/bin/sh
echo " **************************************"
echo " * Install skin oZeta-FHD by mmark     *"
echo " * Don't Remove this Disclaimer        *"
echo " * ************ by lululla *************"
fldlulu='/usr/lib/enigma2/python/Plugins/PLi'
if grep -qs -i "openpli" /etc/issue; then
  echo "OpenPLI image"
  cp -rf /tmp/tmp/oPLI/* /usr/share/enigma2/oZeta-FHD > /dev/null 2>&1
fi
if [ -d $fldlulu ]; then
  echo "distro= OpenPLI image"
  cp -rf /tmp/tmp/usr / > /dev/null 2>&1
  cp -rf /tmp/tmp/oPLI/* /usr/share/enigma2/oZeta-FHD > /dev/null 2>&1
fi
if grep -qs -i "openatv" /etc/image-version; then
 echo "distro= Openatv image"
 if grep -qs -i "version=6" /etc/image-version; then
  echo "distro= Openatv image < 6.4"
  cp -rf /tmp/tmp/usr / > /dev/null 2>&1
  cp -rf /tmp/tmp/oATV/* /usr/share/enigma2/oZeta-FHD > /dev/null 2>&1
  cp -rf /usr/share/enigma2/oZeta-FHD/zSkin/skin_teamatv6.xml /usr/share/enigma2/oZeta-FHD/zSkin/skin_team.xml > /dev/null 2>&1
 fi
 if grep -qs -i "version=7" /etc/image-version; then
  echo "distro= Openatv image > 7.x"
  cp -rf /tmp/tmp/usr / > /dev/null 2>&1
  cp -rf /tmp/tmp/oATV/* /usr/share/enigma2/oZeta-FHD > /dev/null 2>&1
 fi 
fi
if grep -qs -i "openspa" /etc/issue; then
 echo "distro= Openspa image"
 cp -rf /tmp/tmp/usr / > /dev/null 2>&1
 cp -rf /tmp/oSPA /usr/share/enigma2/oZeta-FHD > /dev/null 2>&1
fi
if grep -qs -i "egami" /etc/issue; then
 echo "distro= Egami image"
 cp -rf /tmp/tmp/usr / > /dev/null 2>&1
 cp -rf /tmp/oEgami /usr/share/enigma2/oZeta-FHD > /dev/null 2>&1
fi
sleep 2
rm -r /var/volatile/tmp/*.ipk > /dev/null 2>&1
echo "*****************************************"
echo "*                                       *"
echo "*      oZeta setup installed            *"
echo "*       please restart gui              *"
echo "*****************************************"
exit 0
